# cosmo_utils config for landscape.io code quality check

doc-warnings: false
test-warnings: false
strictness: medium
max-line-length: 80

ignore-paths:
    - dev
    - examples
    - docs/conf.py
    - imageutils/extern
    - imageutils/version.py
    - imageutils/conftest.py
    - imageutils/_astropy_init.py
    - imageutils/cython_version.py
    - ah_bootstrap.py
    - ez_setup.py

python-targets:
  - 3