name: cosmo_utils

channels:
    - astropy
    - conda-forge

dependencies:
    - python >= 3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - h5py
    - pandas
#   - pip:
#       - dependency_from_pip
